
TRANSLATION_SERVICE_YANDEX = 'Yandex'
TRANSLATION_SERVICE_GOOGLE = 'Google'
TRANSLATION_SERVICE_BING = 'Bing'
TRANSLATION_SERVICE_DEEPL = 'Deepl'

TRANSLATOR_BY_SERVICE_NAME = [
    TRANSLATION_SERVICE_YANDEX,
    TRANSLATION_SERVICE_GOOGLE,
    TRANSLATION_SERVICE_BING,
    TRANSLATION_SERVICE_DEEPL
]